java_library(
  name = "testutil",
  srcs = glob(["**/*.java"]),
  visibility = ["//visibility:public"],
  deps = [
    "//persistentworkers/src/main/java/persistent/common:persistent-common",
    "//persistentworkers/src/main/java/persistent/bazel:bazel-persistent-workers",
    "@maven//:com_google_truth_truth",
    "@maven//:commons_io_commons_io",
    "@maven//:org_mockito_mockito_core",
  ],
)
