name: Build and Push Base Buildfarm Worker Images

on:
  push:
    branches:
      - main
    paths:
      - ci/base-worker-image/jammy/Dockerfile
      - ci/base-worker-image/mantic/Dockerfile
jobs:
  build:
    if: github.repository == 'bazelbuild/bazel-buildfarm'
    name: Build Base Buildfarm Worker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Bazelbuild Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BAZELBUILD_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BAZELBUILD_DOCKERHUB_TOKEN }}

      - name: Build Jammy Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./ci/base-worker-image/jammy/Dockerfile
          push: true
          tags: bazelbuild/buildfarm-worker-base:jammy

      - name: Build Mantic Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./ci/base-worker-image/mantic/Dockerfile
          push: true
          tags: bazelbuild/buildfarm-worker-base:mantic
